kind: Deployment
apiVersion: apps/v1
metadata:
  name: httpd-deployment-helm
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd-helm
  template:
    metadata:
      labels:
        app: httpd-helm
    spec:
      containers:
        - name: httpd-container
          image: {{ .Values.image }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%