kind: Deployment
apiVersion: apps/v1
metadata:
  name: istio-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd-istio-deployment
  template:
    metadata:
      labels:
        app: httpd-istio-deployment
      annotations:
        sidecar.istio.io/inject: 'true'
    spec:
      containers:
        - name: httpd-container
          image: registry.redhat.io/rhscl/httpd-24-rhel7