apiVersion: v1
kind: Pod
metadata:
  name: istio-pod
  labels:
    app: istio-pod-example
  annotations:
    sidecar.istio.io/inject: 'true'
spec:
  containers:
    - name: istio-pod-example
      image: registry.redhat.io/rhscl/httpd-24-rhel7
      ports:
        - containerPort: 8080
